version: "3"
services:
  tableapp:
    image: tableapp
    build:
      context: tableapp
      dockerfile: Dockerfile-dev
    ports:
      - "3200:3000"
    # restart: always
    environment:
      - TZ=Asia/Tokyo
    stdin_open: true
    volumes:
      - ./tableapp/src:/SimpleTableApp/src
  nginxrp:
    image: nginxrp
    build:
      context: tableapp
      dockerfile: Dockerfile-pro
    ports:
      - "80:80"
    # restart: always
    environment:
      - TZ=Asia/Tokyo
